# hello-go-deploy-gae task-deploy.yml

platform: linux

# DOCKER BASE IMAGE FOR TASKS (BASED ON ALPINE, A SMALLER LINUX DISTRIBUTION)
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.20.1

inputs:
  - name: hello-go-deploy-gae

run:
  path: ./hello-go-deploy-gae/ci/scripts/deploy.sh
  # args: [-debug]
