# hello-go-deploy-gae task-deploy.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: jeffdecola/go-gcloud-packer
    tag: latest

params:
  GCP_JEFFS_APP_SERVICE_ACCOUNT_FILE: "this will be overwritten"
  GCP_JEFFS_APP_SERVICE_ACCOUNT_EMAIL_ADDRESS: "this will be overwritten"
  GCP_JEFFS_PROJECT_ID: "this will be overwritten"
  
inputs:
- name: hello-go-deploy-gae

run:
  path: ./hello-go-deploy-gae/ci/scripts/deploy.sh
  # args: [-debug]

